import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ThemeContext } from "../contexts";
import { useContext } from "react";
import HeatMap from "../components/HeatMap";

const Home: NextPage = () => {
  const context = useContext(ThemeContext);

  return (
    <div>
      <Head>
        <title>Constant</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h3>constant</h3>
        <HeatMap />
      </main>
    </div>
  );
};

export default Home;
